### ISSUE TITLE
JUnitTestsElectionsDaoFile à verfier.

### ISSUE THREAD

**Issue by adelbigbos** [ProjetPooGroupe3/elections#12]
Veuillez vérifier le fichier JUnitTestsElectionsDaoFile

**Comment by scarykiller** [comment]
En fait il est déja présent dans le projet "test" ce fichier ^^ tu l'as vu?

**Comment by adelbigbos** [comment]
désolé j ai pas capter.

**Comment by scarykiller** [comment]
Ok donc je le refuse ^^
