### ISSUE TITLE
Classe ListeElectorale (verifier la méthode setNom).

### ISSUE THREAD

**Issue by adelbigbos** [ProjetPooGroupe3/elections#13]
pour la méthode setNom de la classe ListeElectorale  je pense que c'est mieux d'utiliser les méthodes la classe String (exemple .equals, .length)
`
public void setNom(String nom) throws ElectionsException {
		if(nom == "" || nom == null)
			throw new ElectionsException("Nom blanc ou vide");
		this.nom = nom;
}`

**Comment by scarykiller** [comment]
Je viens de le changer normalement, je te laisse vérifier mon changement

**Comment by adelbigbos** [comment]
oui parfait.
