### ISSUE TITLE
Important : Réussir à modifier GetSeuilElectoral

### ISSUE THREAD

**Issue by scarykiller** [ProjetPooGroupe3/elections#15]
Je n'arrive pas à le modifier.
Quoique je fasse, il rend 0.0 .

HELP PLEASE

**Comment by speedeu87** [comment]
montre ton code !

**Comment by scarykiller** [comment]
J'ai bien les fichiers java et pas les .classe.
Tu peux trouver les fichiers sur github.
Essaye simplement de faire un return d'un double autre que 0.0 avec la classe JUnit en modifiant le seuilElectoral.
ça fait 4h que je tourne en rond sans comprendre pourquoi ma méthode n'est jamais utilisée ^^

**Comment by scarykiller** [comment]
(je ne publie pas ce que je fais actuellement pour la simple et bonne raison que je comptais recommencer à partir de ce point-ci vu que je ne trouvais pas de solution ^^ )

**Comment by scarykiller** [comment]
Aucune réponse?
Merci...

**Comment by adelbigbos** [comment]
je suis la man
